# Generated by Django 4.1.6 on 2023-02-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('laptop', 'laptop'), ('camera', 'camera'), ('tablet', 'tablet'), ('headphones', 'headphones'), ('phone', 'phone'), ('mouse', 'mouse'), ('console', 'console'), ('other', 'other')], max_length=50, null=True)),
                ('cost', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/products')),
                ('desc', models.CharField(max_length=255)),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
