# Generated by Django 4.1.6 on 2023-02-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('samsung', 'samsung'), ('apple', 'apple'), ('lg', 'lg'), ('sony', 'sony'), ('hp', 'hp'), ('panasonic', 'panasonic'), ('huawei', 'huawei'), ('xiaomi', 'xiaomi'), ('nokia', 'nokia'), ('lenovo', 'lenovo'), ('other', 'other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'laptop'), ('camera', 'camera'), ('tablet', 'tablet'), ('headphones', 'headphones'), ('phone', 'phone'), ('mouse', 'mouse'), ('console', 'console'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
